/*DROP TABLE IF EXISTS EMPLOYEES;*/
  
CREATE TABLE EMPLOYEES (
  employeeid INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  gender VARCHAR(250) NOT NULL,
  dob date NOT NULL,
  department VARCHAR(250) NOT NULL
);